import os
import json
import logging
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import git
from github import Github
import google.generativeai as genai

from .config import Config

logger = logging.getLogger(__name__)

class GitHubProjectEvaluator:
    AI_INDICATORS = [
        'generated by ai', 'chatgpt', 'gpt-4', 'gpt-3', 'claude', 'copilot generated',
        '// AI-generated', '# AI-generated', '/* Generated by', 'auto-generated by',
        '// This code was generated', '# This code was generated'
    ]

    def __init__(self):
        self.github_token = Config.GITHUB_TOKEN
        self.clone_dir = Config.CLONE_DIR
        self.github = Github(self.github_token) if self.github_token else None
        self.ai_provider = Config.AI_PROVIDER
        self.openai_client = None
        self.openai_model = Config.OPENAI_MODEL

        if self.ai_provider == 'openai':
            if not Config.OPENAI_API_KEY:
                raise ValueError("OPENAI_API_KEY is required when AI_PROVIDER=openai")
            self.openai_client = OpenAI(api_key=Config.OPENAI_API_KEY)
        Path(self.clone_dir).mkdir(parents=True, exist_ok=True)

    def parse_github_url(self, repo_url: str) -> Tuple[str, str]:
        repo_url = repo_url.strip().rstrip('/').removesuffix('.git')
        if 'github.com' in repo_url:
            parts = repo_url.split('github.com/')[-1].split('/')
            if len(parts) >= 2:
                return parts[0], parts[1]
        raise ValueError(f"Invalid GitHub URL: {repo_url}")

    def clone_repo(self, repo_url: str, team_name: str) -> str:
        local_path = os.path.join(self.clone_dir, team_name.replace(' ', '_'))
        if os.path.exists(local_path):
            shutil.rmtree(local_path)
        git.Repo.clone_from(repo_url, local_path, depth=1)
        return local_path

    def analyze_contributors(self, repo_url: str) -> Dict:
        if not self.github:
            return {}
        owner, repo_name = self.parse_github_url(repo_url)
        repo = self.github.get_repo(f"{owner}/{repo_name}")
        contributors_data = {}
        for contributor in repo.get_contributors():
            commits = list(repo.get_commits(author=contributor)[:50])
            total_additions = 0
            total_deletions = 0
            files_modified = set()
            important_file_changes = 0
            trivial_commits = 0
            for commit in commits:
                files = commit.files
                commit_additions = 0
                commit_deletions = 0
                has_important_files = False
                for f in files:
                    commit_additions += f.additions
                    commit_deletions += f.deletions
                    files_modified.add(f.filename)
                    if self._is_important_file(f.filename):
                        has_important_files = True
                        important_file_changes += 1
                if commit_additions + commit_deletions < 5 and not has_important_files:
                    trivial_commits += 1
                total_additions += commit_additions
                total_deletions += commit_deletions
            quality_score = self._calculate_commit_quality(
                len(commits), important_file_changes, trivial_commits, 
                total_additions, total_deletions
            )
            contributors_data[contributor.login] = {
                "name": contributor.name or contributor.login,
                "commits": len(commits),
                "additions": total_additions,
                "deletions": total_deletions,
                "net_lines": total_additions - total_deletions,
                "files_modified": len(files_modified),
                "important_file_changes": important_file_changes,
                "trivial_commits": trivial_commits,
                "quality_score": quality_score,
                "sample_commits": [],
                "contribution_percentage": 0
            }
        total_commits = sum(c["commits"] for c in contributors_data.values())
        if total_commits > 0:
            for data in contributors_data.values():
                data["contribution_percentage"] = round((data["commits"] / total_commits) * 100, 2)
        return contributors_data

    def _is_important_file(self, filename: str) -> bool:
        important_extensions = {'.py', '.js', '.jsx', '.ts', '.tsx', '.java', '.cpp', '.c', '.cs', '.php', '.rb', '.go', '.rs'}
        trivial_patterns = ['README', '.md', '.txt', '.json', 'package-lock', '.css', '.scss', '.gitignore', 'LICENSE']
        if any(filename.endswith(ext) for ext in important_extensions):
            return True
        if any(pattern in filename for pattern in trivial_patterns):
            return False
        return True

    def _calculate_commit_quality(self, total_commits: int, important_changes: int, 
                                   trivial_commits: int, additions: int, deletions: int) -> float:
        if total_commits == 0:
            return 0.0
        important_ratio = (important_changes / total_commits) * 40 if total_commits > 0 else 0
        non_trivial_ratio = ((total_commits - trivial_commits) / total_commits) * 30 if total_commits > 0 else 0
        avg_lines_per_commit = (additions + deletions) / total_commits if total_commits > 0 else 0
        if 20 <= avg_lines_per_commit <= 200:
            volume_score = 30
        elif avg_lines_per_commit < 20:
            volume_score = (avg_lines_per_commit / 20) * 30
        else:
            volume_score = max(0, 30 - ((avg_lines_per_commit - 200) / 100))
        return round(important_ratio + non_trivial_ratio + volume_score, 2)

    def cleanup_clone(self, local_path: str):
        if os.path.exists(local_path):
            shutil.rmtree(local_path)
